description: >
  AWStats Web Statistics Server.

  This server hosts AWStats web-statistics application and stores customer
  statistics databases.
includes: [ wincommon, wpe.managed.fw ]
firewall:
- name: tcp_out_backnet_web_servers
  description: TCP connections in backnet to web servers
  direction: outgoing
  networks: [backnet]
  ports: 21,1024-65535
  connect_with: {roles: [wsng, hewsl, winweb, cf, wssfe]}
- name: tcp_out_frontnet_web_servers
  description: TCP connections in frontnet to web servers
  direction: outgoing
  networks: [frontnet]
  ports: 80
  connect_with: {roles: [wsng, hewsl]}
- name: tcp_in_frontnet
  description: TCP connections in frontnet to web servers
  type: internet
  networks: [frontnet]
  ports: 80,443
  connect_with: {hosts: [any]}
requirements:
  OS_SP: "^Microsoft Windows Server 2012 R2 (Standard|Datacenter)$"
  OSLanguage: en-US
  architecture: 64-bit
  networks: [backnet, frontnet]
  cpu-cores: 2
  cpu-frequency: 2.3
  ram(GB): 2
  'C:': 40
  'D:': 100

