description: >
  Customer Active Directory Integration Server

  It runs the Customer AD Synchronization Web Service.
includes: [ wincommon ]
firewall:
- name: to_mn_api
  networks: [backnet]
  direction: outgoing
  ports: 8440
  connect_with: {roles: [linmn]}
- name: to_cdiws
  type: internet
  ports: 443
  connect_with: { hosts: any }
requirements:
  OS_SP: "^Microsoft Windows Server 2008.*(Standard|Enterprise|Datacenter)$"
  OSLanguage: en-US
  cpu-frequency: 2
  ram(GB): 1
  'C:': 80
  networks: [backnet, frontnet]
