description: Checks for PACI Parallels Cloud Server Storage Node role
includes: [ lincommon, lin.oa.managed.fw, vz.fw ]
firewall:
- name: incoming
  networks: [backnet]
  ports: 64000,22
  connect_with: {roles: [oaci_bn_vz, oaci_vz]}
requirements:
  OS: 'Virtuozzo Linux release 7\.'
  ram(GB): 2
  swap(GB): 4
  cpu-frequency: 1.5
  /: 12
  /vz: 1400
  networks: [backnet]
  storage_roles: { type: manual, value: 'Be sure to use vzstorage roles servers.yaml if VZ storage cluster is used' }
