description: Checks for HENAS role, NFS server for Linux NG Webcluster
includes: [ lincommon ]
firewall:
  - name: Incoming_from_HEWSL
    description: "Allow access to NFS share from cluster's webservers"
    networks: [backnet]
    protos: [TCP,UDP]
    ports: 111,2049,10300-10305
    connect_with:
      roles: [hewsl]
requirements:
  OS: '(CentOS|Red Hat Enterprise Linux Server).* 6\.'
  virtualization: 'bare metal'
  ram(GB): 16
  swap(GB): 32
  /: 80
  networks: [backnet, frontnet]
  websites_disk: { type: manual, value: 'There should be block device for websites, 10 TB per 20000, check manually' }
