description: Checks for LINDNS role, linux DNS server
includes: [ lincommon, lin.oa.managed.fw ]
firewall:
  - name: Incoming_from_internet_to_LINDNS
    description: Allow access to DNS from outer network
    networks: [frontnet]
    protos: [TCP, UDP]
    ports: 53
    type: internet
    connect_with:
      hosts: any
requirements:
  OS: '(CentOS|Red Hat Enterprise Linux Server).* 7\.[234]'
  ram(GB): 2
  swap(GB): 4
  cpu-cores: 2
  cpu-frequency: 2.3
  /var: 26
  /: 4
  networks: [backnet, frontnet]
