description: >
  DNS Server on Linux

  https://download.automation.odin.com/oa/7.2/oapremium/portal/en/hardware_requirements/60444.htm
  https://download.automation.odin.com/oa/7.2/oapremium/portal/en/firewall_configuration/63158.htm
includes: [ lincommon, lin.oa.managed.fw ]
firewall:
  - name: Incoming_from_internet_to_LINDNS
    description: Allow access to DNS from outer network
    networks: [frontnet]
    protos: [TCP, UDP]
    ports: 53
    type: internet
    connect_with:
      hosts: any
requirements:
  OS: '(CentOS|Red Hat Enterprise Linux Server).* 7\.[234]'
  ram(GB): 2
  swap(GB): 4
  cpu-cores: 2
  cpu-frequency: 2.3
  /var: 26
  /: 4
  networks: [backnet, frontnet]
