description: Checks for LINMN role, linux management node
includes: [ lincommon ]
requirements:
  OS: '(CentOS|Red Hat Enterprise Linux Server).* 7\.[234]'
  ram(GB): 8
  swap(GB): 16
  cpu-cores: 4
  cpu-frequency: 2.3
  /: 5
  /usr: 20
  /var: 150
  networks: [backnet]
  disable_ipv6: { type: eq, parameter: 'network:disable_ipv6', value: "1" }
  cert_oa: { type: manual, value: 'SSL certificate is needed for control panel' }
firewall:
- name: gr_tcp_out_backnet
  description: Group for outgoing TCP connections in backnet
  group: yes
  networks: [backnet]
  direction: outgoing
  rules:  
  - ports: 25,465
    connect_with: {roles: [smtp]}
  - ports: 443
    connect_with: {roles: [aeh]}
  - ports: 389,3268
    connect_with: {roles: [ad]}
  - ports: 5224,5643,5743,5843 
    connect_with: {roles: [balinfe]}
  - ports: 3306
    connect_with: {roles: [mysql]}
  - ports: 5432
    connect_with: {roles: [pgsql, linmndb]}
  - ports: 8008
    connect_with: {roles: [linpps]}
  - ports: 389
    connect_with: {roles: [linmailldap]}
  - ports: 4433-4435
    connect_with: {roles: [vzlin, vzlinbu]}
  - ports: 4432
    connect_with: {roles: [oaci_im]}
  - ports: 48480
    connect_with: {roles: [wpesrvdb, wpesrv]}
- name: gr_tcp_in_backnet
  description: Group for incoming connections in backnet
  group: yes
  networks: [backnet]
  direction: incoming
  rules:
  - ports: 6308
    connect_with: {roles: [aeh]}
  - ports: 8080
    connect_with: {roles: [deployment_workstation]}
- name: pa_download
  description: allow access to pa repo
  direction: outgoing
  networks: [backnet]
  type: internet
  ports: 80,443
  connect_with: {hosts: [download.automation.odin.com]}
- name: smtp_relay
  description: >
    connection to external SMTP relay.

    This rule will allways fail, it is here to be shown with show-firewall
  networks: [backnet]
  direction: outgoing
  type: internet
  ports: 25,465
  connect_with: { hosts: [ smtp.relay ] }

