description: >
  Odin Automation UI Server with branding on Linux.

  https://download.automation.odin.com/oa/7.2/oapremium/portal/en/hardware_requirements/89069.htm
includes: [ lincommon, lin.oa.managed.fw, linui.fw, cp.fw ]
requirements:
  OS: '(CentOS|Red Hat Enterprise Linux Server).* 7\.[234]'
  ram(GB): 16
  swap(GB): 32
  cpu-cores: 4
  cpu-frequency: 2.2
  /: 4
  /var: 40
  networks: [backnet, frontnet]
