description: >
  Office 365 Application Endpoint Host

  http://download.automation.odin.com/poa/Office365_APS2/doc/93670.htm
  http://download.automation.odin.com/poa/Office365_APS2/doc/93732.htm
  http://download.automation.odin.com/poa/Office365_APS2/doc/93733.htm
  http://download.automation.odin.com/poa/Office365_APS2/doc/93735.htm
includes: [ wincommon ]
firewall:
- name: outgoing
  group: yes
  direction: outgoing
  networks: [backnet]
  rules:
  - connect_with: {roles: [smtp]}
    ports: 25,587
  - connect_with: {roles: [webftp]}
    ports: 80,21,1024-65535
  - connect_with: {roles: [branding,linui,linuicln,linuilb]}
    ports: 443
  - connect_with: {roles: [linmn, linmnapp]}
    ports: 6308,8440
  - connect_with: {roles: [balinfe]}
    ports: 5224
  - connect_with: {roles: [o365mssql]}
    ports: 1433
- name: incoming
  networks: [backnet]
  ports: 443
  connect_with: {roles: [linmn, linmnapp]}
- name: mosi_crest_graph
  direction: outgoing
  type: internet
  ports: 443
  connect_with: 
    hosts: 
    - login.microsoftonline.com
    - graph.windows.net
    - login.windows.net
    - partnerapi.store.microsoft.com
    - api.cp.microsoft.com
    - api.partnercenter.microsoft.com
    - login.microsoftonline.de
    - graph.cloudapi.de
    - partner.partnercenterapi.microsoftonline.cn
    - login.chinacloudapi.cn
    - graph.chinacloudapi.cn
- name: public
  networks: [frontnet]
  type: internet
  ports: 443
  connect_with: {hosts: any}
requirements:
  OS_SP: "^Microsoft Windows Server (2008 R2 Web Service Pack 1|2012 R2 Standard)$"
  architecture: 64-bit
  OSLanguage: en-US
  cpu-cores: 2
  cpu-frequency: 2.3
  ram(GB): 4
  'C:': 80
  networks: [backnet, frontnet]
  sql_distr: { type: manual, value: 'Distribution for MS SQL can be required' }
  csp_frontnet: { type: manual, value: 'Frontnet is not required for CSP' }
  csp_frontnet: { type: manual, value: 'Firewall rules are specific for national clouds (outgoing connections to MS services).' }
