description: Checks for Office 365 Application End-point Host
includes: [ wincommon ]
firewall:
- name: outgoing
  group: yes
  direction: outgoing
  rules:
  - networks: [frontnet]
    ports: 443
    connect_with: {roles: [branding]}
  - networks: [backnet]
    ports: 6308
    connect_with: {roles: [linmn]}
  - networks: [backnet]
    ports: 5224
    connect_with: {roles: [balinfe]}
  - networks: [backnet]
    ports: 1433
    connect_with: {roles: [o365mssql]}
- name: incoming
  networks: [backnet]
  ports: 443
  connect_with: {roles: [linmn]}
- name: mosi_crest_graph
  direction: outgoing
  type: internet
  ports: 443
  connect_with: {hosts: [mosi.microsoftonline.com, graph.windows.net, api.cp.microsoft.com]}
- name: public
  networks: [frontnet]
  type: internet
  ports: 443
  connect_with: {hosts: any}
requirements:
  OS_SP: "^Microsoft Windows Server (2008 R2 Web Service Pack 1|2012 R2 Standard)$"
  architecture: 64-bit
  OSLanguage: en-US
  cpu-cores: 2
  cpu-frequency: 2.3
  ram(GB): 4
  'C:': 80
  networks: [backnet, frontnet]
  sql_distr: { type: manual, value: 'Distribution for MS SQL can be required' }
  csp_frontnet: { type: manual, value: 'Frontnet is not required for CSP' }
