description: Firewall rules for OA managed server
internal: yes
firewall:
- name: with_MN
  description: Allow connections to/from pleskd from MN
  group: yes
  networks: [backnet]
  ports: 8352-8439,8441-8500
  connect_with: { roles: [linmn, linmnapp] }
  rules:
  - direction: outgoing
  - direction: incoming
- name: Outgoing_to_LinMN
  description: Specific connections to lin MN
  direction: outgoing
  networks: [backnet]
  ports: 80,16384
  connect_with: { roles: [linmn, linmnapp] }
