description: Firewall rules for privacy proxy server
internal: yes
firewall:
- name: incoming
  networks: [backnet]
  ports: 8008
  connect_with:
    roles: [linmn, vzlin, vzlinbu]
- name: Outgoing_to_BA
  direction: outgoing
  networks: [frontnet]
  ports: 443,8443
  connect_with:
    roles: [balinfe]
- name: apscatalog
  direction: outgoing
  networks: [frontnet]
  ports: 80
  type: internet
  connect_with:
    hosts: [apscatalog.com]
