description: Firewall for UI
firewall:
- name: from_ui
  direction: outgoing
  networks: [backnet]
  group: yes
  rules:
  - name: to_apsc
    ports: 6308
    connect_with: { roles: [linmn] }
  - name: to_privoxy
    ports: 8008
    connect_with: { roles: [linpps] }
- name: to_ui
  networks: [backnet]
  ports: 8080
  connect_with: { roles: [branding, linwdg, webmail_login] }
