description: Firewall rules for VZ server
internal: yes
firewall:
- name: Outgoing_to_Internet
  direction: outgoing
  networks: [backnet, frontnet]
  type: internet
  group: yes
  rules:
  - ports: 5224,7050
    connect_with: {hosts: [ka.virtuozzo.com]}
  - ports: 80,443
    connect_with: {hosts: [repo.virtuozzo.com, vzdownload.swsoft.com, vzup2date.parallels.com]}
  - ports: 8443
    connect_with: {hosts: [subscription.virtuozzo.com]}
