description: Checks for WINFM role,  Windows FileManager Server
includes: [ wincommon, wpe.managed.fw ]
firewall:
- name: gr_tcp_out_backnet
  networks: [backnet]
  direction: outgoing
  ports: 21,1024-65535
  connect_with: {roles: [winweb]}
requirements:
  OS_SP: "^Microsoft Windows Server 2012 R2 (Standard|Datacenter)$"
  architecture: 64-bit
  OSLanguage: en-US
  cpu-cores: 2
  cpu-frequency: 2.3
  ram(GB): 2
  'C:': 80
  networks: [backnet, frontnet]
