description: Checks for WINWEB role,  Windows Web Server
includes: [ wincommon, wpe.managed.fw ]
firewall:
- name: gr_tcp_out_backnet
  description: Group for outgoing TCP connections in backnet
  group: yes
  networks: [backnet]
  direction: outgoing
  rules:
  - ports: 3306
    connect_with: {roles: [mysql]}
  - ports: 5432
    connect_with: {roles: [pgsql]}
  - ports: 1433
    connect_with: {roles: [mssql, mssqlcluster ]}
  - ports: 21,1024-65535
    connect_with: {roles: [awstats]}
- name: Incoming_from_public
  description: "Allow access to hosting services"
  networks: [frontnet]
  ports: 80,443,21,1299,1024-65535
  type: internet
  connect_with:
      hosts: any
requirements:
  OS_SP: "^Microsoft Windows Server 2012 R2 (Standard|Datacenter)$"
  architecture: 64-bit
  OSLanguage: en-US
  cpu-cores: 2
  cpu-frequency: 2.3
  ram(GB): 4
  'C:': 40
  'D:': 260
  networks: [backnet, frontnet]
