description: Checks for WSNG role, linux NG standalone webserver
includes: [ lincommon, lin.oa.managed.fw, ngwebserver.fw ]
requirements:
  OS: 'Cloud Linux 6\.'
  virtualization: 'bare metal'
  ram(GB): 32
  swap(GB): 64
  cpu-cores: 4
  cpu-frequency: 2.2
  /: 5
  /var/log: 10
  /var/www/vhosts: 500
  networks: [backnet, frontnet]
  branding_ui: { type: manual, value: 'If webserver is used for UI+branding, 16 GB of RAM and 1 GB for vhosts will be enough. +10GB for /usr' }
  branding_ui_fw: { type: manual, value: 'Be sure to use auxiliay roles branding and ui in servers.yaml while checking firewall' }
