version: 2
general:
  branches:
    only:
    - circleci

jobs:
  build:
    docker:
    - image: gorilych/circleci-centos7-python
  working_directory: ~/repo
  steps:
  - checkout
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "requirements.txt" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  - run:
      name: create virtualenv
      command: |
        virtualenv --no-site-packages --always-copy --unzip-setuptools --prompt='(hwswa2)' virtualenv
        virtualenv --relocatable virtualenv
        source virtualenv/bin/activate
        pip install -r requirements.txt
        virtualenv --relocatable virtualenv
  - save_cache:
      paths:
      - ./virtualenv
      key: v1-dependencies-{{ checksum "requirements.txt" }}
  # run tests!
  - run:
    name: create distribution archive
    command: |
      git archive --prefix hwswa2/ --format tar --output hwswa2.tar HEAD
      tar --append -f hwswa2.tar --transform 's,^\.,hwswa2,' ./virtualenv/
      gzip --to-stdout hwswa2.tar > hwswa2.tgz && rm -f hwswa2.tar
  - store_artifacts:
    path: hwswa2.tgz
    destination: builds
